# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/wayanchen/Desktop/comp3981_project/Abalone/venv/lib/python3.13/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /Users/wayanchen/Desktop/comp3981_project/Abalone/venv/lib/python3.13/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wayanchen/Desktop/comp3981_project/Abalone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wayanchen/Desktop/comp3981_project/Abalone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	venv/lib/python3.13/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wayanchen/Desktop/comp3981_project/Abalone/CMakeFiles /Users/wayanchen/Desktop/comp3981_project/Abalone//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wayanchen/Desktop/comp3981_project/Abalone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named abalone_ai

# Build rule for target.
abalone_ai: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 abalone_ai
.PHONY : abalone_ai

# fast build rule for target.
abalone_ai/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/build
.PHONY : abalone_ai/fast

cpp_backend/AbaloneAI.o: cpp_backend/AbaloneAI.cpp.o
.PHONY : cpp_backend/AbaloneAI.o

# target to build an object file
cpp_backend/AbaloneAI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/AbaloneAI.cpp.o
.PHONY : cpp_backend/AbaloneAI.cpp.o

cpp_backend/AbaloneAI.i: cpp_backend/AbaloneAI.cpp.i
.PHONY : cpp_backend/AbaloneAI.i

# target to preprocess a source file
cpp_backend/AbaloneAI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/AbaloneAI.cpp.i
.PHONY : cpp_backend/AbaloneAI.cpp.i

cpp_backend/AbaloneAI.s: cpp_backend/AbaloneAI.cpp.s
.PHONY : cpp_backend/AbaloneAI.s

# target to generate assembly for a file
cpp_backend/AbaloneAI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/AbaloneAI.cpp.s
.PHONY : cpp_backend/AbaloneAI.cpp.s

cpp_backend/AbaloneAIPybindWrapper.o: cpp_backend/AbaloneAIPybindWrapper.cpp.o
.PHONY : cpp_backend/AbaloneAIPybindWrapper.o

# target to build an object file
cpp_backend/AbaloneAIPybindWrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/AbaloneAIPybindWrapper.cpp.o
.PHONY : cpp_backend/AbaloneAIPybindWrapper.cpp.o

cpp_backend/AbaloneAIPybindWrapper.i: cpp_backend/AbaloneAIPybindWrapper.cpp.i
.PHONY : cpp_backend/AbaloneAIPybindWrapper.i

# target to preprocess a source file
cpp_backend/AbaloneAIPybindWrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/AbaloneAIPybindWrapper.cpp.i
.PHONY : cpp_backend/AbaloneAIPybindWrapper.cpp.i

cpp_backend/AbaloneAIPybindWrapper.s: cpp_backend/AbaloneAIPybindWrapper.cpp.s
.PHONY : cpp_backend/AbaloneAIPybindWrapper.s

# target to generate assembly for a file
cpp_backend/AbaloneAIPybindWrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/AbaloneAIPybindWrapper.cpp.s
.PHONY : cpp_backend/AbaloneAIPybindWrapper.cpp.s

cpp_backend/Board.o: cpp_backend/Board.cpp.o
.PHONY : cpp_backend/Board.o

# target to build an object file
cpp_backend/Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/Board.cpp.o
.PHONY : cpp_backend/Board.cpp.o

cpp_backend/Board.i: cpp_backend/Board.cpp.i
.PHONY : cpp_backend/Board.i

# target to preprocess a source file
cpp_backend/Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/Board.cpp.i
.PHONY : cpp_backend/Board.cpp.i

cpp_backend/Board.s: cpp_backend/Board.cpp.s
.PHONY : cpp_backend/Board.s

# target to generate assembly for a file
cpp_backend/Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/Board.cpp.s
.PHONY : cpp_backend/Board.cpp.s

cpp_backend/TranspositionTable.o: cpp_backend/TranspositionTable.cpp.o
.PHONY : cpp_backend/TranspositionTable.o

# target to build an object file
cpp_backend/TranspositionTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/TranspositionTable.cpp.o
.PHONY : cpp_backend/TranspositionTable.cpp.o

cpp_backend/TranspositionTable.i: cpp_backend/TranspositionTable.cpp.i
.PHONY : cpp_backend/TranspositionTable.i

# target to preprocess a source file
cpp_backend/TranspositionTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/TranspositionTable.cpp.i
.PHONY : cpp_backend/TranspositionTable.cpp.i

cpp_backend/TranspositionTable.s: cpp_backend/TranspositionTable.cpp.s
.PHONY : cpp_backend/TranspositionTable.s

# target to generate assembly for a file
cpp_backend/TranspositionTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abalone_ai.dir/build.make CMakeFiles/abalone_ai.dir/cpp_backend/TranspositionTable.cpp.s
.PHONY : cpp_backend/TranspositionTable.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... abalone_ai"
	@echo "... cpp_backend/AbaloneAI.o"
	@echo "... cpp_backend/AbaloneAI.i"
	@echo "... cpp_backend/AbaloneAI.s"
	@echo "... cpp_backend/AbaloneAIPybindWrapper.o"
	@echo "... cpp_backend/AbaloneAIPybindWrapper.i"
	@echo "... cpp_backend/AbaloneAIPybindWrapper.s"
	@echo "... cpp_backend/Board.o"
	@echo "... cpp_backend/Board.i"
	@echo "... cpp_backend/Board.s"
	@echo "... cpp_backend/TranspositionTable.o"
	@echo "... cpp_backend/TranspositionTable.i"
	@echo "... cpp_backend/TranspositionTable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

